export const ADMIN_MESSAGE_JOBS_VERSION = '004_admin_message_jobs';

export const ADMIN_MESSAGE_JOBS_STATEMENTS = [
  `CREATE TABLE admin_message_jobs (
    id TEXT PRIMARY KEY,
    kind TEXT NOT NULL CHECK (kind IN ('confirmation', 'organization_list')),
    state TEXT NOT NULL CHECK (state IN ('pending', 'sent', 'failed', 'uncertain')),
    operation_nonce TEXT NOT NULL UNIQUE,
    immutable_input_sha256 TEXT NOT NULL CHECK (length(immutable_input_sha256) = 64),
    recipient_fingerprint TEXT NOT NULL CHECK (length(recipient_fingerprint) = 64),
    document_format TEXT NOT NULL DEFAULT 'pdf' CHECK (document_format = 'pdf'),
    document_sha256 TEXT CHECK (document_sha256 IS NULL OR length(document_sha256) = 64),
    terms_version TEXT,
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    lease_token TEXT,
    lease_expires_at TEXT,
    provider_message_id TEXT,
    acceptance_evidence TEXT CHECK (acceptance_evidence IS NULL OR acceptance_evidence = 'validated-document-status'),
    last_error_code TEXT,
    last_error_message TEXT,
    last_attempt_at TEXT,
    sent_at TEXT,
    created_by_session_id TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    CHECK ((lease_token IS NULL) = (lease_expires_at IS NULL)),
    CHECK (last_error_message IS NULL OR last_error_message = 'Error del proveedor al enviar el documento.'),
    FOREIGN KEY (created_by_session_id) REFERENCES admin_sessions(id) ON DELETE RESTRICT
  )`,
  `CREATE TABLE admin_message_job_registrations (
    job_id TEXT NOT NULL,
    registration_id TEXT NOT NULL,
    ordinal INTEGER NOT NULL CHECK (ordinal >= 0),
    purpose TEXT NOT NULL CHECK (purpose IN ('confirmation_recipient', 'organization_list_member')),
    PRIMARY KEY (job_id, registration_id),
    UNIQUE (job_id, ordinal),
    FOREIGN KEY (job_id) REFERENCES admin_message_jobs(id) ON DELETE RESTRICT,
    FOREIGN KEY (registration_id) REFERENCES barber_signups(id) ON DELETE RESTRICT
  )`,
  `CREATE TABLE admin_message_job_attempts (
    id TEXT PRIMARY KEY,
    job_id TEXT NOT NULL,
    attempt_no INTEGER NOT NULL CHECK (attempt_no > 0),
    attempt_key TEXT NOT NULL UNIQUE,
    trigger TEXT NOT NULL CHECK (trigger IN ('initial', 'admin_retry', 'admin_reconcile')),
    outcome TEXT NOT NULL CHECK (outcome IN ('in_progress', 'sent', 'failed', 'uncertain')),
    provider_message_id TEXT,
    acceptance_evidence TEXT CHECK (acceptance_evidence IS NULL OR acceptance_evidence = 'validated-document-status'),
    error_code TEXT,
    error_message TEXT,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    CHECK (error_message IS NULL OR error_message = 'Error del proveedor al enviar el documento.'),
    UNIQUE (job_id, attempt_no),
    FOREIGN KEY (job_id) REFERENCES admin_message_jobs(id) ON DELETE RESTRICT
  )`,
  `CREATE INDEX admin_message_jobs_state_updated_at_idx ON admin_message_jobs (state, updated_at)`,
  `CREATE INDEX admin_message_job_registrations_registration_idx ON admin_message_job_registrations (registration_id, job_id)`,
  `CREATE INDEX admin_message_job_attempts_job_attempt_no_idx ON admin_message_job_attempts (job_id, attempt_no)`,
];
